import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Auth layout",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="grid grid-cols-1 md:grid-cols-2 h-screen">
        <div className="flex flex-col items-center justify-center">
          {children}
        </div>
        <div className="bg-violet-500 w-full">
          <div className="bg-[url('/images/free-login.png')] bg-no-repeat b-cover bg-center h-full w-full hidden md:block" />
        </div>
      </div>
  );
}
